{% set name = "simba_pbg" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/adamlerer/{{ name }}/archive/refs/tags/v{{ version }}.zip"
  sha256: 7a86b0ff2fddcebc30d7f6961a14cf2ab36d1dd84f3213b4d18d20e0617e5a93

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv"
  
requirements:
  build:
    - {{ compiler('c') }}
    - pytorch >=1.7.1
  host:
    - python
    - pip
  run:
    - python
    # - numpy >=1.12
    # - attrs >=18.2
    # - h5py >=2.8
    # - tqdm
    # - torchvision

test:
  imports:
    - torchbiggraph

about:
  home: https://github.com/adamlerer/simba_pbg
  dev_url: https://github.com/adamlerer/simba_pbg
  license: BSD-3
  license_family: BSD
  summary: A customized PyTorch-BigGraph (PBG) package for `simba`
