{% set name = "simba_pbg" %}
{% set version = "1.0.1.dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/pinellolab/{{ name }}/archive/v{{ version }}.zip"
  sha256: 06e591d321a79be4978e36ab6f5654774b988710890061fdab99da62e369e528

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"
  
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.12
    - pytorch >=1.7.0
    - attrs >=18.2
    - h5py >=2.8
    - tqdm
    - torchvision

test:
  imports:
    - torchbiggraph

about:
  home: https://github.com/pinellolab/simba_pbg
  dev_url: https://github.com/pinellolab/simba_pbg
  license: BSD-3
  license_family: BSD
  summary: A customized PyTorch-BigGraph (PBG) package for `simba`
