{% set name = "simba_pbg" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/adamlerer/{{ name }}/archive/refs/tags/v{{ version }}.zip"
  sha256: 1b21daa782e21ca22efb356800a2dc979ad9b13b8366f3466e17fa71a1d884e1

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv"
  
requirements:
  build:
    - {{ compiler('c') }}
    - pytorch >=1.7.1
  host:
    - python
    - pip
  run:
    - python
    # - numpy >=1.12
    # - attrs >=18.2
    # - h5py >=2.8
    # - tqdm
    # - torchvision

test:
  imports:
    - torchbiggraph

about:
  home: https://github.com/adamlerer/simba_pbg
  dev_url: https://github.com/adamlerer/simba_pbg
  license: BSD-3
  license_family: BSD
  summary: A customized PyTorch-BigGraph (PBG) package for `simba`
